apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-llama-cpp-python
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-vm-csi
