Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.ssh.forward_x11 = true

#---------- minikube ----------
  config.vm.define "minikube" do |server|
    server.vm.network "private_network", ip: "192.168.33.10"
    server.vm.hostname = "minikube"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 8192
      vb.cpus = 4
    end
    server.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install -y docker.io
      usermod -aG docker vagrant
      apt install -y git 
      apt install -y software-properties-common
      #apt-add-repository --yes --update ppa:ansible/ansible
      #apt install -y ansible
      apt install -y curl
      curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-arm64
      install minikube-linux-arm64 /usr/local/bin/minikube && rm minikube-linux-arm64
      cat <<EOF >> /home/vagrant/.bashrc 
alias kubectl="minikube kubectl --"
source <(kubectl completion bash) 
export XAUTHORITY=/home/vagrant/.Xauthority
EOF
      apt install -y bash-completion 
      apt install -y xserver-xorg x11-xserver-utils x11-apps
      cat <<EOF >> /etc/ssh/sshd_config
X11Forwarding yes
X11DisplayOffset 10
X11UseLocalhost no
EOF
      apt install -y nfs-common
      apt install -y chromium-browser
    SHELL
  end
#-------------------------

end
